# Generated by Django 5.1.1 on 2024-10-02 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_rename_timestamp_log_criacao_log_timezone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='timezone',
        ),
    ]
