# Generated by Django 5.1.1 on 2024-10-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenHome',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('cnpj_cpf', models.CharField(max_length=14)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('validade', models.DateTimeField()),
                ('data_uso', models.DateTimeField(blank=True, null=True)),
                ('usado', models.BooleanField(default=False)),
            ],
        ),
    ]
