# Generated by Django 5.1.1 on 2024-10-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuscaCPF_Todos_Emails_Chatbot_JSON',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condominio', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=20)),
                ('bloco', models.CharField(max_length=4)),
                ('unidade', models.CharField(max_length=6)),
                ('tipo', models.CharField(max_length=1)),
                ('gerente', models.CharField(max_length=20)),
                ('nome_gerente', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=8000)),
            ],
        ),
    ]
